[WIP] Simplify generated code for variable declarations with initialization expressions
viperproject/gobra pull request #572
Opened 2022-11-11 14:32 UTC by jcp19

2022-11-11 18:10 UTC, Dspil approved these changes

2022-11-12 23:25 UTC, Felalolf requested changes
The desugarer is not the place to generate inhales to encode assignments. This is clearly part of the encoding. I liked your idea of adding an argument to the initialize node. I think you should do that instead.

2022-11-12 23:36 UTC, Felalolf commented
Also, I would not mix code analysis and the desugarer. The necessary information for the desugaring step should be collecting by the Info object. The main concern is that the desugarer is getting way too complicated and hard to maintain.

2022-11-12 23:50 UTC, Felalolf commented on src/main/scala/viper/gobra/frontend/Desugar.scala
> +        in.Inhale(eq)(newInfo)
If it is ultra urgent, then you could introduce another internal node, e.g. "InitialAssignment" and then replace the inhales with that. That would still be an ugly solution, but at it maintaines the separation of purposes somewhat.

2023-02-14 14:10 UTC, jcp19 commented
This may be a nice use-case for quasi-havoc

2025-04-02 08:17 UTC, closed without merging