Flag for non-linear integer arithmetic
viperproject/gobra pull request #709
Opened 2023-12-01 22:09 UTC by Dspil

Introduces a flag to disable non-linear integer arithmetic.

2023-12-02 13:53 UTC, jcp19 requested changes

2023-12-02 13:53 UTC, jcp19 commented on src/main/scala/viper/gobra/frontend/Config.scala
> +    descr = "Disable non-linear integer arithmetics. Non compatible using Z3 via API or Carbon",
Why doesn't it work with Z3 through API?

2023-12-02 13:53 UTC, jcp19 commented on src/main/scala/viper/gobra/frontend/Config.scala
> +    }
```suggestion
    if (disableNL.toOption.contains(true) && !z3APIMode.toOption.contains(true) && isSiliconBasedBackend) {
      Right(())      
    } else {
      Left("--disableNL is not compatible with Z3 via API or Carbon")
    }
```

2023-12-02 13:53 UTC, jcp19 commented on src/test/resources/regressions/examples/disableNL.gobra
> +ensures 0 <= res && res <= 100 // would fail with --disableNL
Here, we can definitely add an annotation making this run with `--disableNL` and then we can add an expected post-condition failure

2023-12-02 14:05 UTC, Dspil commented on src/main/scala/viper/gobra/frontend/Config.scala
> +    descr = "Disable non-linear integer arithmetics. Non compatible using Z3 via API or Carbon",
We don't have a good way to pass these kinds of settings using the API.

2023-12-02 15:38 UTC, jcp19 commented on src/main/scala/viper/gobra/frontend/Config.scala
> +    }
oops, you are right, should be fixed now

2023-12-05 13:15 UTC, jcp19 approved these changes
LGTM

2023-12-05 13:20 UTC, merged